name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'tools/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_ci:
          - emacs-24-1
          - emacs-24-2
          - emacs-24-3
          - emacs-24-4
          - emacs-24-5
          - emacs-25-1
          - emacs-25-2
          - emacs-25-3
          - emacs-26-1
          - emacs-26-2
          - emacs-26-3
          - emacs-snapshot
        include:
          - emacs_ci: emacs-24-1
            lint_ignore: 1
          - emacs_ci: emacs-24-2
            lint_ignore: 1
    env:
      EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - uses: cachix/cachix-action@v2
      with:
        name: emacs-ci
    - name: Run tests
      # TODO: make an "install-emacs" action
      run: |
        nix-env -iA "${{ matrix.emacs_ci }}" -f https://github.com/purcell/nix-emacs-ci/archive/master.tar.gz
        ./run-tests.sh
