name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'tools/*'

env:
  EMACS_CI: emacs-26-3 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        emacs_ci:
          - emacs-24-1
          - emacs-24-2
          - emacs-24-3
          - emacs-24-4
          - emacs-24-5
          - emacs-25-1
          - emacs-25-2
          - emacs-25-3
          - emacs-26-1
          - emacs-26-2
          - emacs-26-3
          - emacs-snapshot
        include:
          - emacs_ci: emacs-24-1
            lint_ignore: 1
          - emacs_ci: emacs-24-2
            lint_ignore: 1
    env:
      EMACS_CI: ${{ matrix.emacs_ci }}
      EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      # TODO: move the setup to a single handy script in the nix-emacs-ci repo
      run: |
        sh <(curl https://nixos.org/nix/install)
        source ~/.nix-profile/etc/profile.d/nix.sh
        bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
        ./run-tests.sh
